# Generated by Django 5.2.1 on 2025-05-28 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TastyTradeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('sandbox', 'Sandbox')], default='prod', max_length=16)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('access_token', models.CharField(blank=True, max_length=512, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tastytrade_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
