# Generated by Django 5.2.1 on 2025-05-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastytrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastytradecredential',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
