# Generated by Django 5.2.1 on 2025-05-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastytrade', '0002_tastytradecredential_last_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tastytrade_account_number', models.CharField(max_length=32)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('option', 'Option'), ('future', 'Future'), ('crypto', 'Crypto'), ('other', 'Other')], max_length=16)),
                ('symbol', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('average_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('theta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('call', 'Call'), ('put', 'Put')], max_length=4, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastytrade.tastytradecredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'tastytrade_account_number', 'asset_type', 'symbol'], name='tastytrade__user_id_133bb9_idx')],
                'unique_together': {('user', 'credential', 'tastytrade_account_number', 'asset_type', 'symbol', 'expiry', 'strike', 'option_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tastytrade_account_number', models.CharField(max_length=32)),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('transaction_type', models.CharField(choices=[('trade', 'Trade'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('interest', 'Interest'), ('other', 'Other')], max_length=16)),
                ('symbol', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trade_date', models.DateTimeField()),
                ('asset_type', models.CharField(blank=True, max_length=16)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('call', 'Call'), ('put', 'Put')], max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastytrade.tastytradecredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trade_date'],
                'indexes': [models.Index(fields=['user', 'tastytrade_account_number', 'transaction_type', 'symbol'], name='tastytrade__user_id_81f8da_idx')],
            },
        ),
    ]
