# Generated by Django 5.2.1 on 2025-05-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastytrade', '0003_position_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='daily_unrealized_pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='previous_close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
