# Generated by Django 5.2.1 on 2025-05-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastytrade', '0004_position_current_price_position_daily_unrealized_pnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='cash_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
