# Generated by Django 5.2.1 on 2025-05-30 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastytrade', '0005_position_cash_collected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_accounts', models.JSONField(default=list, help_text='List of account numbers to sync and track')),
                ('save_credentials', models.BooleanField(default=True, help_text='Whether to save TastyTrade credentials')),
                ('auto_sync_frequency', models.CharField(choices=[('manual', 'Manual Only'), ('daily', 'Daily'), ('hourly', 'Hourly')], default='manual', max_length=20)),
                ('keep_historical_data_on_account_removal', models.BooleanField(default=True, help_text='Keep historical data when removing an account from tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastytrade.tastytradecredential')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tastytrade_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=32)),
                ('is_tracked', models.BooleanField(default=False, help_text='Whether user chose to track this account')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(blank=True, help_text='IRA, Individual, etc.', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='User-friendly name', max_length=100)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastytrade.tastytradecredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'credential', 'is_tracked'], name='tastytrade__user_id_be8a9b_idx')],
                'unique_together': {('user', 'credential', 'account_number')},
            },
        ),
    ]
